name: release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
    - main

jobs:
  goreleaser:
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.17

    - name: Run goreleaser
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          export GORELEASER_ARGS="--rm-dist"
        fi
        make release
